name = "signalboard"
main = "src/index.ts"
compatibility_date = "2025-01-15"

[vars]
DEV_MODE = "true"
FREE_PLAN = "true"

[[d1_databases]]
binding = "DB"
database_name = "signalboard-db"
database_id = "8e774286-4e04-4bde-b8a3-7ddc2c6213ba"

[[vectorize]]
binding = "VECTORIZE"
index_name = "feedback_embeddings"


[ai]
binding = "AI"

[triggers]
crons = ["0 14 * * *"]
